# Basic Settings
title: 'ras68k-ext controller'
titleStyle: 'dark'
buttonStyle: 'primary'
listenPort: 3000
executingMessage: 'Executing...'

# Process Monitoring Settings
processName: 'pi68k-ext'
processActiveMessage: 'Process Status: Running'
processInactiveMessage: 'Process Status: Stopping'
refreshButtonName: 'Refresh'
monitoringCmd: 'sudo /home/pi/proc-web-con/rasp_stat.sh'

# OS Reboot/Shutdown Settings
osRebootShutdownTitle: 'Raspberry Pi Reboot/Shutdown'
osRebootShutdownButtonStyle: 'danger'
rebootCmd: 'sudo reboot'
rebootButtonName: 'Reboot'
rebootConfirmMessage: 'Reboot OK?'
shutdownCmd: 'sudo shutdown -h now'
shutdownButtonName: 'Shutdown'
shutdownConfirmMessage: 'Shutdown OK?'

# Command Definitions
commandsTitle: 'ras68k-ext Start/Stop'
commands:
  - name: 'Start'
    cmd: 'sudo /home/pi/pcmd/pi68k.py start'
    dir: '/home/pi/pcmd'
    timeout: 5000
  - name: 'Stop'
    cmd: 'sudo /home/pi/pcmd/pi68k.py stop'
    dir: '/home/pi/pcmd'
    timeout: 30000
